# Generated by Django 4.2 on 2025-07-20 00:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("academics", "0007_studentadmission_parent"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Complaint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "poster",
                    models.ForeignKey(
                        help_text="User (Admin/Teacher/etc.) who posted the complaint",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posted_complaints",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        help_text="The student this complaint is about",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="complaints",
                        to="academics.studentadmission",
                    ),
                ),
            ],
        ),
    ]
