# Generated by Django 4.2 on 2025-07-15 20:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_user_user_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("teacher", "Teacher"),
                    ("parent", "Parent"),
                    ("student", "Student"),
                    ("registry", "Registry"),
                    ("business manager", "Business Manager"),
                    ("vpi", "VPI"),
                    ("vpa", "VPA"),
                    ("dean", "Dean"),
                    ("it personel", "IT Personel"),
                ],
                default="admin",
                max_length=20,
            ),
        ),
    ]
