# Generated by Django 4.2 on 2025-07-11 23:36

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("academics", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="SchoolFeePayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("student_class", models.CharField(max_length=100)),
                ("payer_name", models.CharField(max_length=255)),
                ("payer_contact", models.CharField(max_length=255)),
                (
                    "receipt_number",
                    models.UUIDField(default=uuid.uuid4, editable=False),
                ),
                ("date", models.DateField()),
                (
                    "semester",
                    models.CharField(
                        choices=[
                            ("1st Semester", "First Semester"),
                            ("2nd Semester", "Second Semester"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "services",
                    models.CharField(
                        choices=[
                            ("School Fee", "School Fee"),
                            ("Activities Fee", "Activities Fee"),
                            ("Wassce Fee", "Wassce Fee"),
                            ("Other  Fee", "Other Fee"),
                        ],
                        max_length=20,
                    ),
                ),
                ("amount_due", models.DecimalField(decimal_places=2, max_digits=10)),
                ("amount_paid", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="academics.studentadmission",
                    ),
                ),
            ],
        ),
    ]
