# Generated by Django 4.2 on 2025-07-11 23:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("academics", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="SchoolFeesData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "semester",
                    models.CharField(
                        choices=[("First", "First"), ("Second", "Second")],
                        max_length=50,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "grade_class",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fees",
                        to="academics.gradeclass",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "semester",
                    models.CharField(
                        choices=[("First", "First"), ("Second", "Second")],
                        max_length=50,
                    ),
                ),
                (
                    "total_fee",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("payer_name", models.CharField(max_length=100)),
                (
                    "amount_paid",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("date", models.DateField(auto_now_add=True)),
                (
                    "balance_fee",
                    models.DecimalField(
                        decimal_places=2, editable=False, max_digits=10
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="academics.studentadmission",
                    ),
                ),
                (
                    "student_class",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="student_class",
                        to="academics.gradeclass",
                    ),
                ),
            ],
        ),
    ]
