# Generated by Django 4.2 on 2025-07-14 07:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("scoolfeedata", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="schoolfeesdata",
            old_name="amount",
            new_name="yearly_school_fee",
        ),
        migrations.RemoveField(
            model_name="schoolfeesdata",
            name="semester",
        ),
    ]
