# Generated by Django 4.2 on 2025-09-30 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoolfeedata', '0002_rename_amount_schoolfeesdata_yearly_school_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='installment',
            field=models.CharField(choices=[('1st Installment', '1st Installment'), ('2nd Installment', '2nd Installment'), ('3rd Installment', '3rd Installment')], default='1st Installment', max_length=50),
        ),
    ]
