# Generated by Django 4.2 on 2025-07-27 19:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reportcard", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="period",
            name="name",
            field=models.CharField(
                choices=[
                    ("1st", "1st"),
                    ("2nd", "2nd"),
                    ("3rd", "3rd"),
                    ("Exam", "Exam"),
                    ("4th", "4th"),
                    ("5th", "5th"),
                    ("6th", "6th"),
                    ("Examm", "Examm"),
                ],
                max_length=100,
                unique=True,
            ),
        ),
    ]
