# Generated by Django 4.2 on 2025-07-27 19:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reportcard", "0002_alter_period_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="period",
            name="name",
            field=models.CharField(
                choices=[
                    ("Period 1", "Period 1"),
                    ("Period 2", "Period 2"),
                    ("Period 3", "Period 3"),
                    ("Exam", "Exam"),
                    ("Period 4", "Period 4"),
                    ("Period 5", "Period 5"),
                    ("Period 6", "Period 6"),
                    ("Examm", "Examm"),
                ],
                max_length=100,
                unique=True,
            ),
        ),
    ]
