# Generated by Django 4.2 on 2025-08-18 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportcard', '0003_alter_period_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradedistribution',
            name='editable_by_teacher',
            field=models.BooleanField(default=False),
        ),
    ]
