# Generated by Django 4.2 on 2025-08-19 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reportcard', '0004_gradedistribution_editable_by_teacher'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gradedistribution',
            old_name='editable_by_teacher',
            new_name='allow_teacher_update',
        ),
    ]
