# Generated by Django 4.2 on 2025-09-04 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0008_alter_studentadmission_options_and_more'),
        ('academicyear', '0001_initial'),
        ('reportcard', '0005_rename_editable_by_teacher_gradedistribution_allow_teacher_update'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gradedistribution',
            options={'ordering': ['academic_year', 'grade_class', 'student', 'subject']},
        ),
        migrations.AddField(
            model_name='gradedistribution',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academicyear.academicyear'),
        ),
        migrations.AddField(
            model_name='gradesreport',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academicyear.academicyear'),
        ),
        migrations.AddField(
            model_name='studentaverage',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academicyear.academicyear'),
        ),
        migrations.AlterUniqueTogether(
            name='gradedistribution',
            unique_together={('student', 'subject', 'period', 'academic_year')},
        ),
    ]
