# Generated by Django 4.2 on 2025-09-05 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reportcard', '0006_alter_gradedistribution_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gradedistribution',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='gradedistribution',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='gradesreport',
            name='academic_year',
        ),
        migrations.RemoveField(
            model_name='studentaverage',
            name='academic_year',
        ),
        migrations.RemoveField(
            model_name='gradedistribution',
            name='academic_year',
        ),
        migrations.RemoveField(
            model_name='gradedistribution',
            name='allow_teacher_update',
        ),
    ]
