# Generated by Django 4.2 on 2025-09-05 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportcard', '0007_alter_gradedistribution_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradedistribution',
            name='allow_teacher_update',
            field=models.BooleanField(default=False),
        ),
    ]
