# Generated by Django 4.2 on 2025-09-06 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reportcard', '0009_gradedistribution_academic_year_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gradedistribution',
            name='academic_year',
        ),
        migrations.RemoveField(
            model_name='gradesreport',
            name='academic_year',
        ),
        migrations.RemoveField(
            model_name='studentaverage',
            name='academic_year',
        ),
    ]
