# Generated by Django 4.2 on 2025-07-11 23:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("classschedule", "0001_initial"),
        ("teacherdata", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="classschedule",
            name="teacher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="teacherdata.teacherdataprocess",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="classschedule",
            unique_together={
                ("teacher", "day_of_week", "start_time", "end_time"),
                ("grade_class", "day_of_week", "period"),
            },
        ),
    ]
