# Generated by Django 4.2 on 2025-07-15 06:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("loan", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="loan",
            name="full_name",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
