# Generated by Django 4.2 on 2025-07-23 14:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chat",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="chat_images/"),
        ),
        migrations.AddField(
            model_name="chat",
            name="read",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="chat",
            name="message",
            field=models.TextField(blank=True, null=True),
        ),
    ]
