# Generated by Django 4.2 on 2025-09-22 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('highlight', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField()),
                ('button_text', models.CharField(default='Join to our School Now', max_length=100)),
                ('image', models.ImageField(upload_to='admissions/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
