# Generated by Django 4.2 on 2025-07-26 05:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("payroll", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payroll",
            name="admin_salary",
        ),
        migrations.RemoveField(
            model_name="salaryadvance",
            name="adminsalary",
        ),
    ]
