# Generated by Django 4.2 on 2025-07-26 06:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payroll", "0002_remove_payroll_admin_salary_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payroll",
            name="support_staff",
        ),
        migrations.AddField(
            model_name="payroll",
            name="support_staff_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
