# Generated by Django 4.2 on 2025-09-11 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academicyear', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='academicyear',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('is_active',), name='only_one_active_academic_year'),
        ),
    ]
