# Generated by Django 4.2 on 2025-07-11 23:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("academics", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="TeacherDataProcess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=80)),
                ("qualification", models.CharField(max_length=50)),
                ("dependent_student", models.CharField(max_length=50)),
                ("salary", models.DecimalField(decimal_places=2, max_digits=10)),
                ("date_add", models.DateField()),
                (
                    "division",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="academics.division",
                    ),
                ),
            ],
        ),
    ]
