# Generated by Django 4.2 on 2025-07-12 16:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("teacherdata", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teacherdataprocess",
            name="username",
            field=models.OneToOneField(
                limit_choices_to={"user_type": "teacher"},
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
