# Generated by Django 4.2 on 2025-07-12 22:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("teacherdata", "0003_alter_teacherdataprocess_username"),
    ]

    operations = [
        migrations.CreateModel(
            name="SupportStaff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=80)),
                ("department", models.CharField(max_length=100)),
                ("dependent_student", models.CharField(max_length=50)),
                ("salary", models.DecimalField(decimal_places=2, max_digits=10)),
                ("date_add", models.DateField()),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="supportstaff_images/"
                    ),
                ),
            ],
        ),
    ]
