# Generated by Django 4.2 on 2025-07-12 22:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("teacherdata", "0004_supportstaff"),
    ]

    operations = [
        migrations.AddField(
            model_name="supportstaff",
            name="contact",
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="teacherdataprocess",
            name="contact",
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
