# Generated by Django 4.2 on 2025-07-15 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("academics", "0001_initial"),
        ("teacherdata", "0005_supportstaff_contact_teacherdataprocess_contact"),
    ]

    operations = [
        migrations.AddField(
            model_name="teacherdataprocess",
            name="subject",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="academics.subject",
            ),
            preserve_default=False,
        ),
    ]
