# Generated by Django 4.2 on 2025-07-15 08:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("academics", "0001_initial"),
        ("teacherdata", "0006_teacherdataprocess_subject"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="teacherdataprocess",
            name="subject",
        ),
        migrations.AddField(
            model_name="teacherdataprocess",
            name="subjects",
            field=models.ManyToManyField(to="academics.subject"),
        ),
    ]
