# Generated by Django 4.2 on 2025-07-15 10:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("academics", "0001_initial"),
        ("teacherdata", "0007_remove_teacherdataprocess_subject_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="teacherdataprocess",
            name="grade_class",
            field=models.ManyToManyField(blank=True, to="academics.gradeclass"),
        ),
    ]
