# Generated by Django 4.2 on 2025-07-15 20:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("academics", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("teacherdata", "0008_teacherdataprocess_grade_class"),
    ]

    operations = [
        migrations.CreateModel(
            name="TeacherLessonPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("topic", models.CharField(max_length=100)),
                ("objectives", models.TextField()),
                ("content", models.TextField()),
                ("teaching_method", models.TextField()),
                ("assessment", models.TextField()),
                ("week", models.CharField(max_length=20)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                (
                    "grade_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="academics.gradeclass",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="academics.subject",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        limit_choices_to={"user_type": "teacher"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lesson_plans",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date_created"],
                "unique_together": {("teacher", "subject", "grade_class", "week")},
            },
        ),
    ]
