# Generated by Django 4.2 on 2025-07-15 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("reportcard", "0001_initial"),
        ("teacherdata", "0009_teacherlessonplan"),
    ]

    operations = [
        migrations.AddField(
            model_name="teacherlessonplan",
            name="period",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="reportcard.period",
            ),
            preserve_default=False,
        ),
    ]
