# Generated by Django 4.2 on 2025-07-25 08:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("academics", "0007_studentadmission_parent"),
        ("teacherdata", "0010_teacherlessonplan_period"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdministrativeSalary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("qualification", models.CharField(max_length=50)),
                ("dependent_student", models.CharField(max_length=50)),
                ("contact", models.CharField(max_length=20)),
                ("salary", models.DecimalField(decimal_places=2, max_digits=10)),
                ("date_add", models.DateField()),
                (
                    "division",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="academics.division",
                    ),
                ),
                (
                    "grade_class",
                    models.ManyToManyField(blank=True, to="academics.gradeclass"),
                ),
                ("subjects", models.ManyToManyField(to="academics.subject")),
                (
                    "user",
                    models.ForeignKey(
                        limit_choices_to={
                            "user_type__in": [
                                "registry",
                                "business manager",
                                "vpi",
                                "vpa",
                                "dean",
                            ]
                        },
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="admin_salaries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
