# Generated by Django 4.2 on 2025-07-25 23:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("teacherdata", "0011_administrativesalary"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="administrativesalary",
            name="division",
        ),
    ]
