# Generated by Django 4.2 on 2025-07-26 05:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("payroll", "0002_remove_payroll_admin_salary_and_more"),
        ("teacherdata", "0012_remove_administrativesalary_division"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AdministrativeSalary",
        ),
    ]
