# Generated by Django 4.2 on 2025-07-27 12:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("academics", "0007_studentadmission_parent"),
        ("teacherdata", "0015_alter_teacherdataprocess_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teacherdataprocess",
            name="subjects",
            field=models.ManyToManyField(blank=True, to="academics.subject"),
        ),
    ]
