# Generated by Django 4.2 on 2025-07-30 06:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("teacherdata", "0019_alter_teacherdataprocess_username"),
    ]

    operations = [
        migrations.RenameField(
            model_name="teacherdataprocess",
            old_name="username",
            new_name="user",
        ),
    ]
