# Generated by Django 4.2 on 2025-07-30 06:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("teacherdata", "0020_rename_username_teacherdataprocess_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="teacherdataprocess",
            old_name="user",
            new_name="username",
        ),
    ]
