# Generated by Django 4.2 on 2025-07-19 04:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("academics", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentadmission",
            name="parent",
            field=models.ForeignKey(
                default=1,
                limit_choices_to=models.Q(("user_type", "student"), _negated=True),
                on_delete=django.db.models.deletion.CASCADE,
                related_name="parent_admissions",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
