# Generated by Django 4.2 on 2025-07-19 05:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("academics", "0002_alter_studentadmission_parent"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="studentadmission",
            name="mother_name",
        ),
        migrations.AddField(
            model_name="studentadmission",
            name="parent_name",
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
