# Generated by Django 4.2 on 2025-07-19 05:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("academics", "0003_remove_studentadmission_mother_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="studentadmission",
            name="parent_name",
        ),
    ]
