# Generated by Django 4.2 on 2025-07-19 07:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("academics", "0004_remove_studentadmission_parent_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentadmission",
            name="mother_name",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="studentadmission",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                help_text="Primary parent/guardian",
                limit_choices_to={"user_type": "parent"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="children",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
