# Generated by Django 4.2 on 2025-07-19 07:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("academics", "0005_studentadmission_mother_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="studentadmission",
            name="parent",
        ),
    ]
