# Generated by Django 4.2 on 2025-07-19 08:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("academics", "0006_remove_studentadmission_parent"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentadmission",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                help_text="The parent or guardian linked to this student",
                limit_choices_to=models.Q(("user_type", "student"), _negated=True),
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="linked_students",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
