# Generated by Django 4.2 on 2025-09-06 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0008_alter_studentadmission_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentadmission',
            options={},
        ),
        migrations.RemoveField(
            model_name='studentadmission',
            name='academic_year',
        ),
    ]
