# Generated by Django 4.2 on 2025-09-07 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academicyear', '0001_initial'),
        ('academics', '0009_alter_studentadmission_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentadmission',
            name='academic_year',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='academicyear.academicyear'),
            preserve_default=False,
        ),
    ]
