# Generated by Django 4.2 on 2025-09-23 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0010_studentadmission_academic_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentadmission',
            name='student_status',
            field=models.CharField(choices=[('Dependent', 'Dependent'), ('Scholarship', 'Scholarship')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
