# Generated by Django 4.2 on 2025-09-24 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0011_studentadmission_student_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentadmission',
            name='student_status',
            field=models.CharField(choices=[('Regular', 'Regular'), ('Dependent', 'Dependent'), ('Scholarship', 'Scholarship')], max_length=50),
        ),
    ]
