# Generated by Django 4.2 on 2025-07-13 23:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("academics", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MonthlyFinancialRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("month", models.CharField(max_length=20)),
                ("year", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "school_fees_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "graduation_fees",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "entrance_fees",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "project_fees_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "activities_fees_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "wacce_fees_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "extra_class_fees_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "donation_income",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "staff_salary_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "salary_advance_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "staff_loan_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "other_expenditures_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FinancialLineItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "type",
                    models.CharField(
                        choices=[("income", "Income"), ("expense", "Expense")],
                        max_length=10,
                    ),
                ),
                ("date", models.DateField()),
                (
                    "financial_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="line_items",
                        to="expenditurereport.monthlyfinancialrecord",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FeesPerGradeClass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("month", models.CharField(max_length=20)),
                ("year", models.IntegerField()),
                ("fees_expected", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "fees_collected",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "grade_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="academics.gradeclass",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Expenditure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("maintenance", "Maintenance"),
                            ("utilities", "Utilities"),
                            ("supplies", "Supplies"),
                            ("events", "Events"),
                            ("transportation", "Transportation"),
                            ("miscellaneous", "Miscellaneous"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("date", models.DateField(auto_now_add=True)),
                (
                    "recorded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
