# Generated by Django 4.2 on 2025-07-14 00:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("academics", "0001_initial"),
        ("expenditurereport", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="feespergradeclass",
            unique_together={("grade_class", "month", "year")},
        ),
        migrations.AlterUniqueTogether(
            name="monthlyfinancialrecord",
            unique_together={("month", "year")},
        ),
        migrations.CreateModel(
            name="SchoolFeePerGradeClass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "yearly_school_fee",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "grade_class",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="academics.gradeclass",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Fee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fee_type",
                    models.CharField(
                        choices=[
                            ("graduation", "Graduation Fee"),
                            ("entrance", "Entrance Fee"),
                            ("project", "Project Fee"),
                            ("activities", "Activities Fee"),
                            ("wacce", "WACCE Fee"),
                            ("extra_class", "Extra Class Fee"),
                        ],
                        max_length=20,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("date_paid", models.DateField(auto_now_add=True)),
                ("remarks", models.TextField(blank=True)),
                (
                    "grade_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="academics.gradeclass",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="academics.studentadmission",
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="feespergradeclass",
            name="fees_expected",
        ),
        migrations.RemoveField(
            model_name="monthlyfinancialrecord",
            name="activities_fees_total",
        ),
        migrations.RemoveField(
            model_name="monthlyfinancialrecord",
            name="entrance_fees",
        ),
        migrations.RemoveField(
            model_name="monthlyfinancialrecord",
            name="extra_class_fees_total",
        ),
        migrations.RemoveField(
            model_name="monthlyfinancialrecord",
            name="graduation_fees",
        ),
        migrations.RemoveField(
            model_name="monthlyfinancialrecord",
            name="project_fees_total",
        ),
        migrations.RemoveField(
            model_name="monthlyfinancialrecord",
            name="wacce_fees_total",
        ),
    ]
