# Generated by Django 4.2 on 2025-07-14 01:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("expenditurereport", "0002_alter_feespergradeclass_unique_together_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="feespergradeclass",
            name="fees_collected",
        ),
    ]
