# Generated by Django 4.2 on 2025-07-14 01:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("expenditurereport", "0003_remove_feespergradeclass_fees_collected"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SchoolFeePerGradeClass",
        ),
    ]
