# Generated by Django 4.2 on 2025-07-14 01:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("expenditurereport", "0004_delete_schoolfeepergradeclass"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="monthlyfinancialrecord",
            name="other_expenditures_total",
        ),
        migrations.RemoveField(
            model_name="monthlyfinancialrecord",
            name="salary_advance_total",
        ),
        migrations.RemoveField(
            model_name="monthlyfinancialrecord",
            name="school_fees_total",
        ),
        migrations.RemoveField(
            model_name="monthlyfinancialrecord",
            name="staff_loan_total",
        ),
        migrations.RemoveField(
            model_name="monthlyfinancialrecord",
            name="staff_salary_total",
        ),
        migrations.AlterField(
            model_name="feespergradeclass",
            name="month",
            field=models.CharField(
                choices=[
                    ("January", "January"),
                    ("February", "February"),
                    ("March", "March"),
                    ("April", "April"),
                    ("May", "May"),
                    ("June", "June"),
                    ("July", "July"),
                    ("August", "August"),
                    ("September", "September"),
                    ("October", "October"),
                    ("November", "November"),
                    ("December", "December"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="monthlyfinancialrecord",
            name="month",
            field=models.CharField(
                choices=[
                    ("January", "January"),
                    ("February", "February"),
                    ("March", "March"),
                    ("April", "April"),
                    ("May", "May"),
                    ("June", "June"),
                    ("July", "July"),
                    ("August", "August"),
                    ("September", "September"),
                    ("October", "October"),
                    ("November", "November"),
                    ("December", "December"),
                ],
                max_length=20,
            ),
        ),
    ]
