# Generated by Django 4.2 on 2025-07-14 07:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("academics", "0001_initial"),
        (
            "expenditurereport",
            "0005_remove_monthlyfinancialrecord_other_expenditures_total_and_more",
        ),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="feespergradeclass",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="feespergradeclass",
            name="semester",
            field=models.CharField(
                choices=[("First", "First"), ("Second", "Second")],
                default=1,
                max_length=10,
            ),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="feespergradeclass",
            unique_together={("grade_class", "semester", "year")},
        ),
        migrations.RemoveField(
            model_name="feespergradeclass",
            name="month",
        ),
    ]
