# Generated by Django 4.2 on 2025-07-14 20:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("expenditurereport", "0006_alter_feespergradeclass_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="fee",
            name="entrance_student_name",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
