# Generated by Django 4.2 on 2025-07-14 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("academics", "0001_initial"),
        ("expenditurereport", "0007_fee_entrance_student_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fee",
            name="student",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="academics.studentadmission",
            ),
        ),
    ]
