# Generated by Django 4.2 on 2025-07-15 03:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("expenditurereport", "0008_alter_fee_student"),
    ]

    operations = [
        migrations.AddField(
            model_name="fee",
            name="balance",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=1,
                help_text="Fee Charge - Amount Paid",
                max_digits=10,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="fee",
            name="fee_charge",
            field=models.DecimalField(
                decimal_places=2,
                default=1,
                help_text="Total fee to be paid",
                max_digits=10,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="fee",
            name="amount",
            field=models.DecimalField(
                decimal_places=2, help_text="Amount paid so far", max_digits=10
            ),
        ),
    ]
