# Generated by Django 4.2 on 2025-07-17 04:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
