# Generated by Django 4.2 on 2025-07-18 01:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("onlinetestlivetest", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="periodictest",
            name="description",
        ),
        migrations.RemoveField(
            model_name="periodictest",
            name="title",
        ),
        migrations.AddField(
            model_name="periodictest",
            name="direction",
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="periodictest",
            name="duration",
            field=models.DurationField(
                blank=True,
                help_text="Allowed time for completing the test (e.g., 1:30:00)",
                null=True,
            ),
        ),
    ]
