# Generated by Django 4.2 on 2025-07-18 01:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("onlinetestlivetest", "0002_remove_periodictest_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="periodictest",
            name="teacher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
