# Generated by Django 4.2 on 2025-07-18 19:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("onlinetestlivetest", "0003_alter_periodictest_teacher"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="correct_answer",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
