# Generated by Django 4.2 on 2025-10-06 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinetestlivetest', '0004_alter_question_correct_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_true_statement',
            field=models.BooleanField(blank=True, help_text='For True/False questions, mark the correct answer as True or False.', null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='matching_pairs',
            field=models.JSONField(blank=True, help_text="For matching questions, store pairs as a list of {'left': 'A', 'right': '1'} items.", null=True),
        ),
        migrations.AlterField(
            model_name='testsection',
            name='question_type',
            field=models.CharField(choices=[('fill_blank', 'Fill in the Blanks'), ('multiple_choice', 'Multiple Choice'), ('true_false', 'True or False'), ('matching', 'Matching'), ('essay', 'Essay'), ('paragraph', 'Paragraph Writing'), ('drawing', 'Drawing / Graph')], max_length=20),
        ),
    ]
