# Generated by Django 4.2 on 2025-10-08 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinetestlivetest', '0005_question_is_true_statement_question_matching_pairs_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('file', models.FileField(upload_to='test_attachments/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.RemoveField(
            model_name='question',
            name='is_true_statement',
        ),
        migrations.RemoveField(
            model_name='question',
            name='matching_pairs',
        ),
        migrations.AlterField(
            model_name='testsection',
            name='question_type',
            field=models.CharField(choices=[('fill_blank', 'Fill in the Blanks'), ('multiple_choice', 'Multiple Choice'), ('essay', 'Essay'), ('paragraph', 'Paragraph Writing'), ('drawing', 'Drawing / Graph')], max_length=20),
        ),
    ]
